package frc.robot.statemachine.superstructure;

public enum SuperstructureState {

	IDLE,
	INTAKE,
	OUTTAKE,
	ARM_PRE_SCORE,
	PRE_SCORE,
	SCORE_WITHOUT_RELEASE,
	SCORE,
	CLOSE_L4,
	POST_ALGAE_REMOVE,
	ALGAE_REMOVE,
	ALGAE_REMOVE_L4,
	POST_ALGAE_REMOVE_L4,
	ALGAE_OUTTAKE,
	ARM_PRE_NET,
	PRE_NET,
	NET_WITHOUT_RELEASE,
	NET_WITH_RELEASE;

}
